#
# CTP2 Developer Makefile
#
# This Makefile automates developer tasks. The actual build uses meson.
#
# Quick start (macOS):
#   make deps        - install dependencies via Homebrew
#   make setup       - configure meson build directory
#   make build       - compile
#   make test        - run tests
#
# Provided targets:
# deps
#   Install build dependencies via Homebrew (macOS).
#   Requires Homebrew to be installed.
#
# setup
#   Configure the meson build directory (build/).
#
# build
#   Compile the project with meson.
#
# test
#   Run the test suite.
#
# bootstrap (legacy)
#   Create autoconf-based buildfiles. Not used for macOS builds.
#
# local
#   Copy relevant files from the source tree to a local installation.
#
# playtest
#   Create a playtest directory with all files for distribution.
#
# purge
#   Remove files generated by autoconf (legacy).
#
# doc
#   Make all the documentation

all:
	#################################### \
	# This Makefile has no default     # \
	# or all target.                   # \
	# See the comments above           # \
	# for a description of its use.    # \
	####################################

# macOS dependency installation via Homebrew
deps:
	@echo "Installing CTP2 build dependencies..."
	@command -v brew >/dev/null 2>&1 || { echo "Homebrew is required but not installed. See https://brew.sh"; exit 1; }
	brew bundle install
	@echo "Dependencies installed."

# Meson build directory setup
setup:
	@echo "Configuring meson build directory..."
	meson setup build ctp2_code --buildtype=debug
	@echo "Configure complete. Run 'make build' to compile."

# Compile the project
build:
	@echo "Building CTP2..."
	meson compile -C build

# Run tests
test: build
	@echo "Running tests..."
	meson test -C build

# Clean build directory
clean-build:
	@echo "Cleaning build directory..."
	rm -rf build

bootstrap-anet: ctp2_code/libs/anet ctp2_code/libs/anet/Makefile
	$(MAKE) -C $< bootstrap
	
bootstrap: bootstrap-anet
	@echo "Bootstraping Civilization Call to Power 2"
	@echo " "
	@echo "This is no official release by activision."
	@echo " "
	aclocal -I ctp2_code/os/autoconf -I ctp2_code/libs/anet/macros
	autoheader
	libtoolize --force --copy
	automake --foreign --add-missing --copy
	autoconf
	@echo " "
	@echo "Bootstraping complete."
	@echo " "
	@echo "You may run ./configure and then make to compile CTP2."

local:
	bin/copy_to_local.sh

PLAYTEST = playtest

playtest:
	$(MAKE) -C doc/user
	-rm -rf playtest
	mkdir -p $(PLAYTEST)/ctp2_program/ctp/dll/
	svn export ctp2_code/ctp/dll $(PLAYTEST)/ctp2_program/ctp/dll --force
	cp -uv ctp2_code/ctp/dll/map/*.dll $(PLAYTEST)/ctp2_program/ctp/dll/map/
	cp -uv ctp2_code/ctp/anet* $(PLAYTEST)/ctp2_program/ctp/
	cp -uv ctp2_code/ctp/ctp2.* $(PLAYTEST)/ctp2_program/ctp/
	cp -uv ctp2_code/ctp/zlib1.dll $(PLAYTEST)/ctp2_program/ctp/
	cp -uv ctp2_code/ctp/jpeg62.dll $(PLAYTEST)/ctp2_program/ctp/
	cp -uv ctp2_code/ctp/libtiff3.dll $(PLAYTEST)/ctp2_program/ctp/
	#cp -uv ctp2_code/ctp/appstr.txt $(PLAYTEST)/ctp2_program/ctp/
	cp -uv doc/user/playtest/*.txt $(PLAYTEST)/
	mkdir -p $(PLAYTEST)/doc
	cp -uv doc/user/manual/user_manual.pdf $(PLAYTEST)/doc
	svn export ctp2_data $(PLAYTEST)/ctp2_data --force
	svn export Scenarios $(PLAYTEST)/Scenarios --force

doc:
	$(MAKE) -C doc

.PHONY: all deps setup build test clean-build local playtest doc

SRCDIRS=\
	ctp2_code \
	ctp2_code/ctp \
	ctp2_code/gfx \
	ctp2_code/gfx/gfx_utils \
	ctp2_code/gs \
	ctp2_code/gs/database \
	ctp2_code/gs/dbgen \
	ctp2_code/gs/events \
	ctp2_code/gs/fileio \
	ctp2_code/gs/gameobj \
	ctp2_code/gs/newdb \
	ctp2_code/gs/outcom \
	ctp2_code/gs/slic \
	ctp2_code/gs/utility \
	ctp2_code/gs/world \
	ctp2_code/mapgen \
	ctp2_code/os \
	ctp2_code/os/nowin32 \
	ctp2_code/sound \
	ctp2_code/ui \
	ctp2_code/ui/interface

MRPROPER_DIRS=\
	autom4te.cache \
	ctp2_code/autom4te.cache \
	$(foreach srcdir,$(SRCDIRS),\
		$(srcdir)/.deps \
		$(srcdir)/.lib \
		$(srcdir)/_lib \
	 )
MRPROPER_FILES=\
	GNUmakefile \
	GNUmakefile.in \
	aclocal.m4 \
	config.log \
	config.status \
	configure \
	libtool \
	ctp2_code/Makefile \
	ctp2_code/Makefile.in \
	ctp2_code/aclocal.m4 \
	ctp2_code/config.log \
	ctp2_code/config.status \
	ctp2_code/configure \
	ctp2_code/libtool \
	ctp2_code/gs/dbgen/ctpdb \
	ctp2_code/gs/dbgen/ctpdb.exe \
	ctp2_code/gs/dbgen/ctpdb_lex.c \
	ctp2_code/gs/dbgen/ctpdb_yacc.c \
	ctp2_code/gs/dbgen/ctpdb_yacc.h \
	ctp2_code/gs/dbgen/lex.yy.c \
	ctp2_code/gs/dbgen/y.tab.c \
	ctp2_code/gs/dbgen/y.tab.h \
	ctp2_code/os/autoconf/config/config.guess \
	ctp2_code/os/autoconf/config/config.sub \
	ctp2_code/os/autoconf/config/depcomp \
	ctp2_code/os/autoconf/config/install-sh \
	ctp2_code/os/autoconf/config/ltmain.sh \
	ctp2_code/os/autoconf/config/missing \
	ctp2_code/os/autoconf/config/mkinstalldirs \
	ctp2_code/os/include/config.h \
	ctp2_code/os/include/config.h.in \
	ctp2_code/os/include/config.h.in~ \
	$(foreach srcdir,$(SRCDIRS),\
		$(srcdir)/*.la \
		$(srcdir)/*.lo \
		$(srcdir)/*.o \
		$(srcdir)/Makefile \
		$(srcdir)/Makefile.in \
		$(srcdir)/so_locations \
	 )

clean:

distclean:

purge: distclean
	@for DIR in $(MRPROPER_DIRS) ; do \
		echo rm -rf $$DIR ; \
		rm -rf $$DIR ; \
	done
	@for FILE in $(MRPROPER_FILES) ; do \
		echo rm -f $$FILE ; \
		rm -f $$FILE ; \
	done
