#
# CTP2 Developer Makefile
#
# This Makefile automates developer tasks. The actual build uses meson.
#
# Quick start (macOS):
#   make deps        - install dependencies via Homebrew
#   make setup       - configure meson build directory
#   make build       - compile
#   make test        - run tests
#
# Provided targets:
# deps
#   Install build dependencies via Homebrew (macOS).
#   Requires Homebrew to be installed.
#
# setup
#   Configure the meson build directory (build/).
#
# build
#   Compile the project with meson.
#
# test
#   Run the test suite.
#
# test-render
#   Every pixel oracle for the renderer. The only tests that look at a
#   presented frame; run after touching gfx/ or ui/aui_sdl/.
#
# trial
#   Very long all-AI soak (8 players, Deity): status table every 10s with
#   turn, cities + best, units, tech level + researching/last, wonders.
#
# test-p13
#   Whole-map transition parity (its own suite, not in test-full).
#
# gateway / gateway-build / gateway-test
#   The Crystal observability gateway (gateway/): `make gateway` builds the
#   game + gateway and serves HTTP on :8666 with a spawned headless game.
#   See gateway/README.md.
#
# bootstrap (legacy)
#   Create autoconf-based buildfiles. Not used for macOS builds.
#
# local
#   Copy relevant files from the source tree to a local installation.
#
# playtest
#   Create a playtest directory with all files for distribution.
#
# purge
#   Remove files generated by autoconf (legacy).
#
# doc
#   Make all the documentation

all:
	#################################### \
	# This Makefile has no default     # \
	# or all target.                   # \
	# See the comments above           # \
	# for a description of its use.    # \
	####################################

# One ccache store for every worktree/build dir — workers jumping
# branches still hit warm objects. Only affects build dirs configured
# with ccache as compiler launcher (fresh `meson setup` auto-detects).
export CCACHE_DIR ?= $(HOME)/.cache/ccache-ctp2

# macOS dependency installation via Homebrew
deps:
	@echo "Installing CTP2 build dependencies..."
	@command -v brew >/dev/null 2>&1 || { echo "Homebrew is required but not installed. See https://brew.sh"; exit 1; }
	brew bundle install
	@echo "Dependencies installed."

# Meson build directory setup
setup:
	@echo "Configuring meson build directory..."
	meson setup build ctp2_code --buildtype=debug
	@echo "Configure complete. Run 'make build' to compile."

# Meson build with AddressSanitizer + UndefinedBehaviorSanitizer + hardening
setup-sanitized:
	@echo "Configuring meson build with sanitizers (ASan + UBSan) + hardening..."
	@rm -rf build-sanitized
	meson setup build-sanitized ctp2_code \
		--buildtype=debug \
		-Db_sanitize=address,undefined \
		-Db_lundef=false \
		-Dcpp_args="-fno-omit-frame-pointer" \
		-Dc_args="-fno-omit-frame-pointer"
	@echo "Sanitized build configured. Run 'make build-sanitized' to compile."

build-sanitized:
	@echo "Building CTP2 with sanitizers..."
	mise exec -- meson compile -C build-sanitized

# UBSan-only build. On some macOS/Apple clang combinations ASan can deadlock in
# dyld before main(); this keeps a sanitizer smoke tier available for CI/local use.
setup-ubsan:
	@echo "Configuring meson build with UndefinedBehaviorSanitizer..."
	@rm -rf build-ubsan
	mise exec -- meson setup build-ubsan ctp2_code \
		--buildtype=debug \
		-Db_sanitize=undefined \
		-Db_lundef=false \
		-Dcpp_args="-fno-omit-frame-pointer" \
		-Dc_args="-fno-omit-frame-pointer"
	@echo "UBSan build configured. Run 'make build-ubsan' to compile."

build-ubsan:
	@echo "Building CTP2 with UBSan..."
	mise exec -- meson compile -C build-ubsan ctp2_headless

# Performance tier (P8). The dev default is -O0 debug with hardening=maximum
# (-ftrapv on every signed op) — measured 5.3x wall / 8.6x CPU slower than
# release on the same seed (identical game outcome, so optimization does not
# break determinism). Use the release tier for play sessions, benchmarks, and
# long soaks; it does NOT replace the hardened dev/test tiers.
# NOTE: buildtype must be `release`, not `debugoptimized` — meson.build gates
# _DEBUG/SHOW_ASSERTS/USE_LOGGING on buildtype.startswith('debug'), which
# `debugoptimized` matches. Thin-LTO measured 2026-07-12: ~7% CPU over plain
# -O2 (user 1.95s vs 2.11s, 60-turn/6-player benchmark) — enabled here since
# this tier is rebuilt occasionally, not per-edit.
setup-release:
	@echo "Configuring optimized release build (thin-LTO)..."
	@rm -rf build-release
	mise exec -- meson setup build-release ctp2_code \
		--buildtype=release \
		-Dhardening_level=basic \
		-Db_lto=true \
		-Db_lto_mode=thin
	@echo "Release build configured. Run 'make release' to compile."

release:
	@test -d build-release || $(MAKE) setup-release
	@echo "Building CTP2 (release)..."
	mise exec -- meson compile -C build-release ctp2 ctp2_headless

# Release-tier validation (run per milestone): the long-game soak + a wide
# seed sweep against the optimized binary. The meson-wired test suites keep
# running the debug tier (with a small 3-seed sweep).
release-check: release
	mise exec -- python3 ctp2_code/test/scenario_long_game.py build-release/ctp2_headless
	mise exec -- python3 ctp2_code/test/scenario_seed_sweep.py build-release/ctp2_headless --count 20 --turns 60 --players 6

# trial: very long all-AI soak tracking tech progress per player.
# 8 AI players at Deity, status table every 10s (turn, cities + best,
# units, tech level + researching/last completed, wonders). Override via
# env, e.g. TRIAL_TURNS=100 TRIAL_PLAYERS=4 make trial (TRIAL_BINARY,
# TRIAL_TURNS, TRIAL_PLAYERS, TRIAL_SEED, TRIAL_DIFFICULTY,
# TRIAL_STATUS_EVERY, TRIAL_BATCH, TRIAL_TIMEOUT). Uses the debug headless
# binary so AI asserts and crashes surface instead of being optimized away.
trial: build
	mise exec -- python3 ctp2_code/test/ai_trial.py build/ctp2_headless

seed-sweep: release
	mise exec -- python3 ctp2_code/test/scenario_seed_sweep.py build-release/ctp2_headless --count 20 --turns 60 --players 6

# Short ASan/UBSan smoke path. Uses the repro harness so failures include the
# headless log/crash report tail instead of just a sanitizer abort.
SAN_CMDS ?= new_game; start_game; query_players; end_turn 2; query_players
SAN_ARGS ?= --players 3 --seed 42
SAN_LOG  ?= /tmp/ctp2_sanitized_smoke.log
SAN_SOCKET_WAIT ?= 180
SAN_OPTIONS ?= detect_leaks=0:halt_on_error=1:abort_on_error=1
UBSAN_OPTIONS ?= halt_on_error=1:abort_on_error=1:print_stacktrace=1
sanitized-smoke: build-sanitized
	@echo "Running ASan/UBSan smoke via build-sanitized/ctp2_headless..."
	ASAN_OPTIONS=$(SAN_OPTIONS) UBSAN_OPTIONS=$(UBSAN_OPTIONS) \
		mise exec -- python3 ctp2_code/test/repro.py build-sanitized/ctp2_headless \
		--cmds '$(SAN_CMDS)' --args '$(SAN_ARGS)' --log '$(SAN_LOG)' \
		--socket-wait $(SAN_SOCKET_WAIT)

ubsan-smoke: build-ubsan
	@echo "Running UBSan smoke via build-ubsan/ctp2_headless..."
	UBSAN_OPTIONS=$(UBSAN_OPTIONS) \
		mise exec -- python3 ctp2_code/test/repro.py build-ubsan/ctp2_headless \
		--cmds '$(SAN_CMDS)' --args '$(SAN_ARGS)' --log '$(SAN_LOG)' \
		--socket-wait $(SAN_SOCKET_WAIT)

# Compile the project
build:
	@echo "Building CTP2..."
	meson compile -C build

# Modernization ratchet — allows cleanup to lower legacy pattern counts, but
# fails if a change adds more raw ownership, unsafe strings, C allocation, or
# type-erased casts.
modernization-ratchet:
	@echo "Checking C++ modernization ratchets..."
	mise exec -- python3 tools/modernization/ratchet.py

modernization-ratchet-update:
	@echo "Updating C++ modernization ratchet baseline..."
	mise exec -- python3 tools/modernization/ratchet.py --update-baseline

# Pre-commit loop — fast + unit + isolated menus (excludes integration / smoke).
# Menu tests use SDL dummy video: licensed assets required, no desktop or game.
#   - fast:  ratchets + observer dispatch tests + small unit cases
#   - unit:  all other test_*.cpp except the headless integration set
#            (test_headless_*.cpp and test_save_load.cpp are tagged
#            doctest::test_suite("integration") and excluded here)
test: modernization-ratchet
	@echo "Building fast + unit tests..."
	meson compile -C build ctp2_fast_tests ctp2_unit_tests ctp2_menu_tests
	@echo "Running fast + unit + isolated menu tests (no integration)..."
	meson test -C build fast unit ui-menu

# Full-game UI integration without a desktop; keeps real simulation/rendering.
test-ui-integration:
	meson compile -C build ctp2
	meson test -C build --no-rebuild --suite ui-integration --print-errorlogs

# One-command crash/behavior repro. Boots serve mode, optionally loads a
# save (path or test/fixtures name), runs a ';'-separated command script.
# On a crash the game log tail includes the in-process crash report.
#   make repro CMDS='end_turn 5; query_players'
#   make repro SAVE=c7-b-r80 CMDS='move_army 0 36 90; end_turn 4'
BIN ?= build/ctp2_headless
REPRO_ARGS ?= --players 3 --seed 42
repro:
	@test -n "$(CMDS)" || { echo "usage: make repro [SAVE=name|path] [BIN=...] CMDS='verb args; verb args'"; exit 2; }
	@python3 ctp2_code/test/repro.py $(BIN) $(if $(SAVE),--save '$(SAVE)') --cmds '$(CMDS)' --args '$(REPRO_ARGS)'

# Slower integration suite — headless game subprocess tests + the in-binary
# "integration" doctest set (save/load, determinism, multi-turn AI).
# ~15-25 minutes.  HIGHER TIER (>60s rule): pre-push / slower cadence, never
# pre-commit.  The pre-commit loop is `make test` (~4s).
test-integration: build
	@echo "Running integration suite (headless game tests)..."
	meson test -C build integration

# UI-only P11 proof: forces GPU camera offsets and verifies presented pixels move,
# then checks the smooth pan path passes through sub-tile positions. Opens the UI
# binary, so keep it out of the fast pre-commit loop.
test-pan-pixel: build
	@echo "Running P11 GPU camera pixel/glide proof..."
	meson test -C build pan-pixel-proof --print-errorlogs

# Every pixel oracle for the renderer, in one target. These are the
# only tests that look at a presented frame, and since P13 became the default
# they guard the whole-map path rather than the ADR-002 window mirror. Run this
# after touching anything under gfx/ or ui/aui_sdl/ — the unit tiers cannot see
# a rendering regression at all.
# Keep the command prefix stable for reusable display-access approval:
#   mise exec -- make test-render
#   mise exec -- make test-render RENDER_TESTS=worldmap-borders
# The isolated installation is prepared once; no personal saves/profile touched.
# Override RENDER_HOME to reuse an existing test installation, or RENDER_DATA
# when the original game data lives outside this checkout.
RENDER_HOME ?= $(CURDIR)/build/render-home
RENDER_DATA ?= $(CURDIR)/ctp2_data
RENDER_TESTS ?= ui-seed slice-ui pan-pixel-proof gpu-world-fallbacks gpu-sprite-refresh gpu-actor-parity gpu-trade-animation terrain-edge-parity \
	worldmap-fog worldmap-borders goods-reload gpu-raster-parity \
	raster-overlay-parity gpu-improvement-parity worldmap-transition-parity
test-render:
	meson compile -C build ctp2 ctp2_render
	@if ! test -d "$(RENDER_HOME)/original_data/default/gamedata" || \
	    ! test -d "$(RENDER_HOME)/assets/current"; then \
		python3 tools/assets/install_ctp2_home.py "$(RENDER_DATA)" \
			--ctp2-home "$(RENDER_HOME)"; \
	fi
	@echo "Running renderer pixel oracles..."
	@render_run=$$(mktemp -d /tmp/ctp2-render.XXXXXX) || exit 1; \
		CTP2_HOME="$(RENDER_HOME)" CTP2_SMOKE_SOCKET="$$render_run/smoke.sock" \
		meson test -C build --no-rebuild $(RENDER_TESTS) --print-errorlogs

# P13 whole-map transition parity (~2 min). Its own suite, deliberately: it
# compares two game processes frame-by-frame and is the most sensitive check
# here, so it should not gate the shipping suite on a bad day. Not included in
# `make test-full` for the same reason — run it explicitly.
test-p13: build
	@echo "Running P13 whole-map transition parity..."
	meson test -C build --suite p13 --print-errorlogs

# Full test suite — fast + unit + integration + smoke + scenario.
# ~20-30 minutes (dominated by the integration tier).  Run pre-release or when
# investigating a regression — not in the fast loop.
test-full: build
	@echo "Running full test suite..."
	meson test -C build

# Coverage build + report.  Uses a separate build-cov directory so the
# default build/ stays fast.  Requires gcovr (`brew install gcovr`).
# (Skips meson's built-in coverage target — it depends on lcov, which trips
# over CTP2's generated headers; gcovr is more tolerant.)
#
# Usage:
#   make coverage             # rebuild + run tests/scenarios + emit summary
#   make coverage-html        # also generate per-file HTML report
#   make coverage-summary     # quick re-print of the latest gs/ + ai/ summary
#   open build-cov/coverage-report/index.html
coverage-setup:
	@test -d build-cov || meson setup build-cov ctp2_code -Db_coverage=true --buildtype=debug

coverage: coverage-setup
	@echo "Building coverage-instrumented targets..."
	meson compile -C build-cov ctp2 ctp2_headless ctp2_fast_tests ctp2_unit_tests
	@echo "Running test suites against coverage build..."
	-meson test -C build-cov fast unit
	@echo "Running headless scenarios for additional coverage..."
	-./build-cov/ctp2_headless --new-game --seed 42 --turns 50 --players 4 --export-metrics /tmp/cov-50.csv
	-./build-cov/ctp2_headless --new-game --seed 99 --turns 25 --players 4 --export-metrics /tmp/cov-25.csv
	-./build-cov/ctp2_headless --new-game --seed 42 --turns 25 --players 4 --save-game /tmp/cov-save.sav
	-./build-cov/ctp2_headless --load-game /tmp/cov-save.sav --turns 25
	@$(MAKE) -s coverage-summary

coverage-summary:
	@command -v gcovr >/dev/null || { echo "gcovr not installed; run: brew install gcovr"; exit 1; }
	@echo "==================================================================="
	@echo "Coverage summary — gs/ + ai/ (the simulation-core, target ≥50%):"
	@echo "==================================================================="
	@gcovr --root . --filter 'ctp2_code/(gs|ai)/' --object-directory build-cov --print-summary 2>/dev/null | tail -4

coverage-html: coverage-setup
	@command -v gcovr >/dev/null || { echo "gcovr not installed; run: brew install gcovr"; exit 1; }
	@mkdir -p build-cov/coverage-report
	@echo "Generating per-file HTML report..."
	@gcovr --root . --filter 'ctp2_code/(gs|ai)/' --object-directory build-cov \
	       --html-details build-cov/coverage-report/index.html 2>&1 | tail -3
	@echo ""
	@echo "Report: build-cov/coverage-report/index.html"

# Run the game (from project root so it finds appstr.txt, civpaths.txt, ctp2_data/)
run: build
	@echo "Starting CTP2 at 1920x1080..."
	@test -f appstr.txt || ln -sf ctp2_code/ctp/appstr.txt appstr.txt
	@./build/ctp2 --resolution 1920x1080

# Visible human play with automatic seed/session recording. The sidecar keeps
# turn checkpoints, passive frames, native input and watchdog diagnostics.
play-record: build
	@mise exec -- python3 ctp2_code/test/play_record.py record --binary build/ctp2 $(PLAY_ARGS)

# Mark the active recording. The monitor captures state/checkpoint/frame; if
# the game is hung this falls back to the last frame plus a process sample.
play-mark:
	@mise exec -- python3 ctp2_code/test/play_record.py mark --note '$(or $(NOTE),reported bug)'

# Continue from the newest turn checkpoint in the latest recorded session.
play-resume: build
	@mise exec -- python3 ctp2_code/test/play_record.py resume --binary build/ctp2

# Run the game at Full HD (1920x1080) with crash logging via run_game.sh
run-hd: build-sanitized
	@echo "Starting CTP2 at 1920x1080 with crash logging..."
	@test -f appstr.txt || ln -sf ctp2_code/ctp/appstr.txt appstr.txt
	@./run_game.sh --resolution 1920x1080

# Record an AI-vs-AI game and render an empire timelapse (PNG frames + mp4).
#   make timelapse                              # 150 turns -> /tmp/ctp2-timelapse
#   make timelapse TURNS=300 TL_TILE=11         # longer, higher-res
#   make timelapse-render                       # re-render the LAST recording
#                                               # (fast; no game run)
TURNS     ?= 150
TL_DIR    ?= /tmp/ctp2-timelapse
TL_FPS    ?= 12
TL_ZOOM   ?= 5            # render zoom 0..5 (5 = native 1:1 tiles, full detail)
TL_MAPW   ?= 0            # final frame width; 0 = 1:1 (no downscale)
TL_REALART?= 1            # 1 = real isometric engine art; 0 = stylized squares
TL_TILE   ?= 9            # tile px for the stylized-square fallback
TL_PLAYER ?= -1           # unfogged whole map. Set to a player id for fogged,
                          # cropped view from that empire's perspective.
timelapse: build
	@mkdir -p $(TL_DIR)
	@test -f appstr.txt || ln -sf ctp2_code/ctp/appstr.txt appstr.txt
	@echo "[timelapse] recording $(TURNS) turns (a game window will open and auto-close)..."
	AUTOPLAY_TURNS=$(TURNS) TIMELAPSE_OUT=$(TL_DIR)/run.jsonl \
		TIMELAPSE_REALART=$(TL_REALART) TIMELAPSE_ZOOM=$(TL_ZOOM) \
		TIMELAPSE_PLAYER=$(TL_PLAYER) \
		mise exec -- python3 tools/timelapse/record.py
	@$(MAKE) timelapse-render

# Re-render from the existing recording — iterate the visual without replaying.
timelapse-render:
	@echo "[timelapse] rendering frames + mp4..."
	TILE=$(TL_TILE) FPS=$(TL_FPS) MAP_TARGET_W=$(TL_MAPW) \
		mise exec -- python3 tools/timelapse/render.py $(TL_DIR)/run.jsonl $(TL_DIR)/frames
	@echo "[timelapse] done -> $(TL_DIR)/frames/timelapse.mp4"

timelapse-caption-smoke:
	@echo "[timelapse] smoke-testing Chronicle caption rendering..."
	mise exec -- python3 tools/timelapse/smoke_caption.py

# Build the Crystal gateway (gateway/bin/ctp2-gateway)
gateway-build:
	@echo "Building ctp2-gateway..."
	cd gateway && mise exec -- shards build

# Run the gateway specs (no game binary required)
gateway-test:
	@echo "Running ctp2-gateway specs..."
	cd gateway && mise exec -- crystal spec

# Full-stack smoke: gateway specs against a REAL headless game
# (HTTP -> GameClient -> socket -> game_controller). Needs the C++ build.
gateway-e2e: build
	@echo "Running ctp2-gateway end-to-end smoke against build/ctp2_headless..."
	cd gateway && CTP2_HEADLESS=../build/ctp2_headless mise exec -- crystal spec spec/e2e_spec.cr spec/zz_athena_runner_spec.cr

# Build everything and serve the gateway with a spawned headless game.
# HTTP on :8666 (override: make gateway GATEWAY_ARGS="--port 9000").
GATEWAY_ARGS ?=
gateway: build gateway-build
	@echo "Starting ctp2-gateway with a spawned headless game..."
	@./gateway/bin/ctp2-gateway --spawn $(GATEWAY_ARGS)

# Clean build directory
clean-build:
	@echo "Cleaning build directory..."
	rm -rf build

bootstrap-anet: ctp2_code/libs/anet ctp2_code/libs/anet/Makefile
	$(MAKE) -C $< bootstrap
	
bootstrap: bootstrap-anet
	@echo "Bootstraping Civilization Call to Power 2"
	@echo " "
	@echo "This is no official release by activision."
	@echo " "
	aclocal -I ctp2_code/os/autoconf -I ctp2_code/libs/anet/macros
	autoheader
	libtoolize --force --copy
	automake --foreign --add-missing --copy
	autoconf
	@echo " "
	@echo "Bootstraping complete."
	@echo " "
	@echo "You may run ./configure and then make to compile CTP2."

local:
	bin/copy_to_local.sh

PLAYTEST = playtest

playtest:
	$(MAKE) -C doc/user
	-rm -rf playtest
	mkdir -p $(PLAYTEST)/ctp2_program/ctp/dll/
	svn export ctp2_code/ctp/dll $(PLAYTEST)/ctp2_program/ctp/dll --force
	cp -uv ctp2_code/ctp/dll/map/*.dll $(PLAYTEST)/ctp2_program/ctp/dll/map/
	cp -uv ctp2_code/ctp/anet* $(PLAYTEST)/ctp2_program/ctp/
	cp -uv ctp2_code/ctp/ctp2.* $(PLAYTEST)/ctp2_program/ctp/
	cp -uv ctp2_code/ctp/zlib1.dll $(PLAYTEST)/ctp2_program/ctp/
	cp -uv ctp2_code/ctp/jpeg62.dll $(PLAYTEST)/ctp2_program/ctp/
	cp -uv ctp2_code/ctp/libtiff3.dll $(PLAYTEST)/ctp2_program/ctp/
	#cp -uv ctp2_code/ctp/appstr.txt $(PLAYTEST)/ctp2_program/ctp/
	cp -uv doc/user/playtest/*.txt $(PLAYTEST)/
	mkdir -p $(PLAYTEST)/doc
	cp -uv doc/user/manual/user_manual.pdf $(PLAYTEST)/doc
	svn export ctp2_data $(PLAYTEST)/ctp2_data --force
	svn export Scenarios $(PLAYTEST)/Scenarios --force

doc:
	$(MAKE) -C doc

# Smoke test: run game under lldb with automated command injection
smoke-test: build
	@echo "Running smoke test..."
	@test -f appstr.txt || ln -sf ctp2_code/ctp/appstr.txt appstr.txt
	@python3 test/smoke_test.py

# Smoke test with sanitizers enabled
smoke-test-sanitized: build-sanitized
	@echo "Running smoke test with sanitizers..."
	@test -f appstr.txt || ln -sf ctp2_code/ctp/appstr.txt appstr.txt
	@ASAN_OPTIONS=detect_leaks=0:abort_on_error=1:print_legend=1 \
		python3 test/smoke_test.py --build-dir=build-sanitized

# --------------------------------------------------------------------------
# Local CI (.ci/) — background daemon runs Tier A on edits and Tier B on
# commits, writing structured state to .ci/state.json.  See .ci/README.md.
# --------------------------------------------------------------------------

ci-start:
	@if [ -f .ci/daemon.pid ] && kill -0 $$(cat .ci/daemon.pid) 2>/dev/null; then \
		echo "daemon already running (PID $$(cat .ci/daemon.pid))"; \
	else \
		nohup .ci/daemon.sh >/dev/null 2>&1 & \
		sleep 1 && echo "daemon started (PID $$(cat .ci/daemon.pid 2>/dev/null))"; \
	fi

ci-stop:
	@if [ -f .ci/daemon.pid ]; then \
		PID=$$(cat .ci/daemon.pid); \
		if kill -0 $$PID 2>/dev/null; then \
			kill $$PID && echo "daemon stopped (PID $$PID)"; \
		else \
			echo "daemon not running (stale pid file)"; \
			rm -f .ci/daemon.pid; \
		fi; \
	else \
		echo "no daemon running"; \
	fi

ci-status:
	@if [ -f .ci/state.json ]; then cat .ci/state.json; else echo '{ "overall_status": "unknown" }'; fi

# Install the daemon as a launchd agent (survives reboots, loads at login).
# Idempotent: regenerates the plist and reloads the agent.
ci-launchd-install:
	@mkdir -p .ci/log ~/Library/LaunchAgents
	@sed "s|__CTP2_ROOT__|$$(pwd)|g" .ci/com.olek.ctp2-ci.plist \
		> ~/Library/LaunchAgents/com.olek.ctp2-ci.plist
	@launchctl bootout gui/$$(id -u)/com.olek.ctp2-ci 2>/dev/null || true
	@launchctl bootstrap gui/$$(id -u) ~/Library/LaunchAgents/com.olek.ctp2-ci.plist
	@echo "launchd agent installed: ~/Library/LaunchAgents/com.olek.ctp2-ci.plist"

ci-launchd-uninstall:
	@launchctl bootout gui/$$(id -u)/com.olek.ctp2-ci 2>/dev/null || true
	@rm -f ~/Library/LaunchAgents/com.olek.ctp2-ci.plist
	@echo "launchd agent removed"

ci-watch:
	@tail -f .ci/log/daemon.log

ci-failures:
	@if ls .ci/failures/*.json >/dev/null 2>&1; then \
		ls -t .ci/failures/*.json | head -1 | xargs cat; \
	else \
		echo '{ "failures": [] }'; \
	fi

ci-reset:
	@rm -f .ci/STATUS_RED .ci/STATUS_YELLOW .ci/state.json .ci/last_head; \
	rm -f .ci/failures/*.json .ci/log/*.log .ci/log/*.xml .ci/log/*.json 2>/dev/null; \
	echo "CI state cleared"

ci-tier-a:
	@.ci/tiers/tier-a.sh && echo "tier-a done"

ci-tier-b:
	@.ci/tiers/tier-b.sh

ci-nightly:
	@.ci/tiers/tier-c.sh

.PHONY: all deps setup build setup-sanitized build-sanitized sanitized-smoke setup-ubsan build-ubsan ubsan-smoke setup-release release release-check seed-sweep test modernization-ratchet modernization-ratchet-update clean-build local playtest doc smoke-test run-hd \
        test-integration test-pan-pixel test-render test-p13 test-full \
        coverage coverage-setup coverage-summary coverage-html run repro \
        timelapse timelapse-render timelapse-caption-smoke \
        gateway gateway-build gateway-test gateway-e2e \
        ci-start ci-stop ci-status ci-watch ci-failures ci-reset ci-tier-a ci-tier-b ci-nightly ci-launchd-install ci-launchd-uninstall

SRCDIRS=\
	ctp2_code \
	ctp2_code/ctp \
	ctp2_code/gfx \
	ctp2_code/gfx/gfx_utils \
	ctp2_code/gs \
	ctp2_code/gs/database \
	ctp2_code/gs/dbgen \
	ctp2_code/gs/events \
	ctp2_code/gs/fileio \
	ctp2_code/gs/gameobj \
	ctp2_code/gs/newdb \
	ctp2_code/gs/outcom \
	ctp2_code/gs/slic \
	ctp2_code/gs/utility \
	ctp2_code/gs/world \
	ctp2_code/mapgen \
	ctp2_code/os \
	ctp2_code/os/nowin32 \
	ctp2_code/sound \
	ctp2_code/ui \
	ctp2_code/ui/interface

MRPROPER_DIRS=\
	autom4te.cache \
	ctp2_code/autom4te.cache \
	$(foreach srcdir,$(SRCDIRS),\
		$(srcdir)/.deps \
		$(srcdir)/.lib \
		$(srcdir)/_lib \
	 )
MRPROPER_FILES=\
	GNUmakefile \
	GNUmakefile.in \
	aclocal.m4 \
	config.log \
	config.status \
	configure \
	libtool \
	ctp2_code/Makefile \
	ctp2_code/Makefile.in \
	ctp2_code/aclocal.m4 \
	ctp2_code/config.log \
	ctp2_code/config.status \
	ctp2_code/configure \
	ctp2_code/libtool \
	ctp2_code/gs/dbgen/ctpdb \
	ctp2_code/gs/dbgen/ctpdb.exe \
	ctp2_code/gs/dbgen/ctpdb_lex.c \
	ctp2_code/gs/dbgen/ctpdb_yacc.c \
	ctp2_code/gs/dbgen/ctpdb_yacc.h \
	ctp2_code/gs/dbgen/lex.yy.c \
	ctp2_code/gs/dbgen/y.tab.c \
	ctp2_code/gs/dbgen/y.tab.h \
	ctp2_code/os/autoconf/config/config.guess \
	ctp2_code/os/autoconf/config/config.sub \
	ctp2_code/os/autoconf/config/depcomp \
	ctp2_code/os/autoconf/config/install-sh \
	ctp2_code/os/autoconf/config/ltmain.sh \
	ctp2_code/os/autoconf/config/missing \
	ctp2_code/os/autoconf/config/mkinstalldirs \
	ctp2_code/os/include/config.h \
	ctp2_code/os/include/config.h.in \
	ctp2_code/os/include/config.h.in~ \
	$(foreach srcdir,$(SRCDIRS),\
		$(srcdir)/*.la \
		$(srcdir)/*.lo \
		$(srcdir)/*.o \
		$(srcdir)/Makefile \
		$(srcdir)/Makefile.in \
		$(srcdir)/so_locations \
	 )

clean:

distclean:

purge: distclean
	@for DIR in $(MRPROPER_DIRS) ; do \
		echo rm -rf $$DIR ; \
		rm -rf $$DIR ; \
	done
	@for FILE in $(MRPROPER_FILES) ; do \
		echo rm -f $$FILE ; \
		rm -f $$FILE ; \
	done
